---
- name: Add kafka group
  group:
    name: "{{ kafka_group }}"

- name: Add kafka user
  user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    shell: /bin/bash
    home: "{{ kafka_install_dir }}"
    password: '!'
    state: present

- name: Create kafka data directory
  file:
    path: "{{ kafka_data_dir }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Create kafka log directory
  file:
    path: "{{ kafka_log_dir }}"
    state: directory
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"


- name: Check if log directory is exists
  stat:
    path: "/var/log/kafka"
  register: kafka_system_log_dir_check

- name: Message log directory is exists
  debug:
    msg: "/var/log/kafka is existsed, skip creating symlink"
  when:
    - kafka_log_dir_symlink
    - kafka_system_log_dir_check.stat.exists

- name: Create log directory symlink
  file:
    path: "{{ kafka_install_dir }}/logs"
    dest: "/var/log/kafka"
    state: link
  when: 
    - kafka_log_dir_symlink
    - not kafka_system_log_dir_check.stat.exists
